#!/bin/bash

if [ -d $OPENSHIFT_REPO_DIR/public/wp-content/uploads ];
    then rm -R $OPENSHIFT_REPO_DIR/public/wp-content/uploads
fi

ln -sf $OPENSHIFT_DATA_DIR/uploads $OPENSHIFT_REPO_DIR/public/wp-content/uploads